# First workflow at Devops course
#flow name
name: CI

# Trigger
on:
  # Triggers the workflow on push or pull request events, but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    # Where the work'll be executed
    runs-on: ubuntu-latest
    
    steps:
      # Check-out
      - uses: actions/checkout@v3

      # Runs the command in the shell
      - name: executando docker 
        run: docker run docker/whalesay cowsay Primeira Atividade de Workflow em DEVOPS IT TALENT

      # Runs a set of commands in the shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
